# Generated by Django 6.0.7 on 2026-07-23 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astra', '0004_produit_reference_vente_client_nom_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='categorie',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
