# Generated by Django 6.0.7 on 2026-07-23 09:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astra', '0005_alter_produit_categorie'),
    ]

    operations = [
        migrations.AddField(
            model_name='vente',
            name='mode_paiement',
            field=models.CharField(default='especes', max_length=50),
        ),
        migrations.CreateModel(
            name='LigneVente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.PositiveIntegerField(default=1)),
                ('prix_unitaire', models.DecimalField(decimal_places=2, max_digits=10)),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='astra.produit')),
                ('vente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='astra.vente')),
            ],
        ),
        migrations.DeleteModel(
            name='DetailVente',
        ),
    ]
