# Generated by Django 6.0.7 on 2026-07-24 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astra', '0006_vente_mode_paiement_lignevente_delete_detailvente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fournisseur',
            name='adresse',
        ),
        migrations.RemoveField(
            model_name='fournisseur',
            name='date_creation',
        ),
        migrations.AddField(
            model_name='fournisseur',
            name='contact',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='approvisionnement',
            name='montant_total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='approvisionnement',
            name='reference',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='approvisionnement',
            name='statut',
            field=models.CharField(choices=[('en_attente', 'En attente'), ('confirmee', 'Confirmée'), ('expediee', 'Expédiée'), ('livree', 'Livrée'), ('annulee', 'Annulée')], default='en_attente', max_length=20),
        ),
        migrations.AlterField(
            model_name='fournisseur',
            name='email',
            field=models.EmailField(default='', max_length=254, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fournisseur',
            name='nom',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='fournisseur',
            name='telephone',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
