# Generated by Django 6.0.7 on 2026-07-26 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astra', '0007_remove_fournisseur_adresse_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TokenVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('token', models.CharField(max_length=6)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('utilise', models.BooleanField(default=False)),
            ],
        ),
    ]
