# Generated by Django 6.0.7 on 2026-07-27 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astra', '0009_remove_vente_client_nom_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vente',
            name='est_archive',
            field=models.BooleanField(default=False),
        ),
    ]
