# Generated by Django 6.0.7 on 2026-07-28 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astra', '0011_remove_client_adresse_remove_client_date_creation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='adresse',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='tokenverification',
            name='role',
            field=models.CharField(default='caissier', max_length=50),
        ),
        migrations.AlterField(
            model_name='client',
            name='telephone',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='tokenverification',
            name='token',
            field=models.CharField(max_length=100),
        ),
    ]
