# Generated by Django 6.0.7 on 2026-07-28 09:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astra', '0012_client_adresse_tokenverification_role_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profil_type', models.CharField(choices=[('etudiant', 'Étudiant'), ('enseignant', 'Enseignant'), ('entreprise', 'Entreprise'), ('admin', 'Admin'), ('candidat', 'Candidat')], default='candidat', max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
