# Generated by Django 6.0.7 on 2026-07-28 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astra', '0013_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('valeur_token', models.CharField(max_length=50, unique=True)),
                ('role', models.CharField(default='utilisateur', max_length=50)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_expiration', models.DateTimeField()),
                ('est_utilise', models.BooleanField(default=False)),
            ],
        ),
    ]
