# Generated by Django 6.0.7 on 2026-07-28 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('astra', '0014_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='token',
            name='est_utilise',
        ),
    ]
