# Generated by Django 6.0.7 on 2026-07-31 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astra', '0015_remove_token_est_utilise'),
    ]

    operations = [
        migrations.AddField(
            model_name='approvisionnement',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='fournisseur',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='produit',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
