# Generated by Django 6.0.7 on 2026-07-31 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astra', '0016_approvisionnement_is_active_fournisseur_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='processeur',
            field=models.CharField(blank=True, help_text='Ex: Intel Core i5-12400F, Apple M1', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='produit',
            name='ram',
            field=models.CharField(blank=True, help_text='Ex: 8Go, 16Go DDR4', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='produit',
            name='stockage_disque',
            field=models.CharField(blank=True, help_text='Ex: SSD 512Go NVMe', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='produit',
            name='taille_ecran',
            field=models.CharField(blank=True, help_text='Ex: 15.6 pouces, 13.3 pouces', max_length=50, null=True),
        ),
    ]
