# Generated by Django 6.0.7 on 2026-08-03 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astra', '0017_produit_processeur_produit_ram_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approvisionnement',
            name='reference',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
