# Generated by Django 6.0.7 on 2026-08-03 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astra', '0018_alter_approvisionnement_reference'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='reference',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
