# Generated by Django 6.0.7 on 2026-08-07 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astra', '0019_client_reference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fournisseur',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='fournisseur',
            name='telephone',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
