# Generated by Django 6.0.7 on 2026-08-07 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astra', '0020_alter_fournisseur_email_alter_fournisseur_telephone'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='mot_de_passe',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
