# Generated by Django 6.0.7 on 2026-08-12 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astra', '0022_notificationplateforme'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParametreGlobal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_boutique', models.CharField(default='ASTRA TECH', max_length=255)),
                ('verrou_commercial', models.BooleanField(default=False)),
                ('verrou_admin', models.BooleanField(default=False)),
                ('seuil_stock', models.IntegerField(default=5)),
                ('taux_tva', models.DecimalField(decimal_places=2, default=19.25, max_digits=5)),
            ],
        ),
    ]
