# Generated by Django 6.0.7 on 2026-08-19 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astra', '0024_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationplateforme',
            name='categorie',
            field=models.CharField(choices=[('ventes', 'Ventes'), ('stocks', 'Stocks'), ('appro', 'Approvisionnement'), ('clients', 'Clients'), ('fournisseurs', 'Fournisseurs'), ('rapports', 'Rapports')], default='ventes', max_length=20),
        ),
        migrations.AlterField(
            model_name='notificationplateforme',
            name='titre',
            field=models.CharField(max_length=200),
        ),
    ]
