# Generated by Django 6.0.7 on 2026-08-19 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astra', '0025_notificationplateforme_categorie_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='date_naissance',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='notificationplateforme',
            name='categorie',
            field=models.CharField(choices=[('ventes', 'Ventes'), ('stocks', 'Stocks'), ('appro', 'Approvisionnement'), ('clients', 'Clients'), ('fournisseurs', 'Fournisseurs'), ('rapports', 'Rapports')], default='clients', max_length=20),
        ),
    ]
