# Generated by Django 6.0.7 on 2026-08-21 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astra', '0026_client_date_naissance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fournisseur',
            name='mot_de_passe',
            field=models.CharField(default='1234', max_length=255),
        ),
    ]
