# Generated by Django 6.0.7 on 2026-08-24 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astra', '0027_fournisseur_mot_de_passe'),
    ]

    operations = [
        migrations.CreateModel(
            name='UtilisateurAcces',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telephone', models.CharField(blank=True, max_length=30)),
                ('role', models.CharField(choices=[('client', 'Client'), ('fournisseur', 'Fournisseur')], max_length=20)),
                ('token', models.CharField(blank=True, max_length=128, unique=True)),
                ('token_expiration', models.DateTimeField(blank=True, null=True)),
                ('est_actif', models.BooleanField(default=True)),
                ('date_inscription', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
