# Generated by Django 6.0.7 on 2026-09-03 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astra', '0028_utilisateuracces'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='telephone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
